-D LANGUAGE=en_us
-D MESSAGESTYLE=neu
-Fy obj -Fo obj
-o UntilValhalla.t3
-lib system
-lib adv3/adv3

-source UntilValhalla

# Things
-source things/chapter1/BirthCertificate
-source things/chapter1/DriversLicense
-source things/chapter1/EnlistmentRequirements
-source things/chapter1/SocialSecurityCard
-source things/chapter1/TranscriptFile

# Achievements
-source achievements/chapter1/NotarizeBirthCertificate
-source achievements/chapter1/CurrentEvents
-source achievements/chapter1/HistoryLesson
-source achievements/chapter1/MilitaryScience
-source achievements/chapter1/ObeyingAuthority
-source achievements/chapter1/WhoAmI

# Characters
-source characters/Me
-source characters/chapter1/BailBondsman
-source characters/chapter1/CountyRecorder
-source characters/chapter1/CourtDefender
-source characters/chapter1/JudgeRockwell
-source characters/chapter1/NewsVendor
-source characters/chapter1/SfcGanci

# Classes
-source classes/Money
-source classes/Signable
-source classes/WritingInstrument

# Library Modifications
-source lib-mods/ImplicitActionMessages

# Rooms
-source rooms/chapter1/BailBondsOffice
-source rooms/chapter1/CourthouseFoyer
-source rooms/chapter1/CourthouseHallway
-source rooms/chapter1/CourthouseRecorderOffice
-source rooms/chapter1/Courtroom
-source rooms/chapter1/GcRecruitingCenter
-source rooms/chapter1/NewsStand
-source rooms/chapter1/OutsideCourthouse
-source rooms/chapter1/OutsideRecruitingCenter

# Verbs
-source verbrules/Purchase
-source verbrules/Sign
